/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 warthog_green.glb --transform -S -s -k 
Files: warthog_green.glb [109.51MB] > /Users/stephen/Downloads/futuristic cars/warthog_green-transformed.glb [3.9MB] (96%)
Author: Alucard (https://sketchfab.com/Ronald.Browen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/warthog-green-aa9f58dce051470ea5c0fed9898e2a84
Title: Warthog - Green
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF(
    "/models/warthog_green_small-transformed.glb"
  ) as any;
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <mesh
        name="HubCap_Front_L_Tires_0"
        castShadow
        receiveShadow
        geometry={nodes.HubCap_Front_L_Tires_0.geometry}
        material={materials.Tires}
        position={[0.781, 0.443, 1.193]}
        rotation={[-1.57, 0, 0]}
        scale={0.654}
      />
      <skinnedMesh
        name="Object_92"
        geometry={nodes.Object_92.geometry}
        material={materials.Glass}
        skeleton={nodes.Object_92.skeleton}
        rotation={[-1.57, 0, 0]}
        scale={0.654}
      />
      <skinnedMesh
        name="Object_94"
        geometry={nodes.Object_94.geometry}
        material={materials.Interior}
        skeleton={nodes.Object_94.skeleton}
        rotation={[-1.57, 0, 0]}
        scale={0.654}
      />
      <skinnedMesh
        name="Object_96"
        geometry={nodes.Object_96.geometry}
        material={materials.Lights}
        skeleton={nodes.Object_96.skeleton}
        rotation={[-1.57, 0, 0]}
        scale={0.654}
      />
      <skinnedMesh
        name="Object_98"
        geometry={nodes.Object_98.geometry}
        material={materials.Body}
        skeleton={nodes.Object_98.skeleton}
        rotation={[-1.57, 0, 0]}
        scale={0.654}
      />
    </group>
  );
}

useGLTF.preload("/models/warthog_green_small-transformed.glb");
